services:
  eureka-server:
    image: ghcr.io/fiwka/eureka-server:latest
    networks:
      - budget
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
  data-service:
    image: ghcr.io/fiwka/data-service:latest
    networks:
      - budget
    environment:
      POSTGRES_HOST: budget-data-pg
      POSTGRES_PORT: 5432
      POSTGRES_DB: budget_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      budget_data_pg:
        condition: service_healthy
      kafka:
        condition: service_healthy
  analytics-service:
    image: ghcr.io/fiwka/analytics-service:latest
    networks:
      - budget
    environment:
      POSTGRES_HOST: budget-analytics-pg
      POSTGRES_PORT: 5432
      POSTGRES_DB: budget_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      budget_analytics_pg:
        condition: service_healthy
      kafka:
        condition: service_healthy
  zookeeper:
    image: zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    hostname: zookeeper
  kafka:
    image: apache/kafka:latest
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:29092"]
      interval: 30s
      retries: 5
      timeout: 10s
  budget_data_pg:
    image: postgres
    hostname: budget-data-pg
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: budget_data
    volumes:
      - ./docker_data/budget_data:/var/lib/postgresql
    networks:
      - budget
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  budget_analytics_pg:
    image: postgres
    hostname: budget-analytics-pg
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: budget_analytics
    volumes:
      - ./docker_data/budget_analytics:/var/lib/postgresql
    networks:
      - budget
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  budget_data_migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    command: --url=jdbc:postgresql://budget-data-pg:5432/budget_data --username=postgres --password=qwerty123 --changelog-file=data/db/master.yaml update
    depends_on:
      budget_data_pg:
        condition: service_healthy
    networks:
      - budget
  budget_analytics_migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    command: --url=jdbc:postgresql://budget-analytics-pg:5432/budget_analytics --username=postgres --password=qwerty123 --changelog-file=analytics/db/master.yaml update
    depends_on:
      budget_analytics_pg:
        condition: service_healthy
    networks:
      - budget
networks:
  budget: