services:
  eureka-server:
    image: ghcr.io/fiwka/eureka-server:latest
    hostname: eureka
    networks:
      - budget
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
  data-service:
    image: ghcr.io/fiwka/data-service:latest
    networks:
      - budget
    environment:
      POSTGRES_HOST: budget-data-pg
      POSTGRES_PORT: 5432
      POSTGRES_DB: budget_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EUREKA_SERVER: eureka:8761
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      budget_data_pg:
        condition: service_healthy
      kafka:
        condition: service_started
  analytics-service:
    image: ghcr.io/fiwka/analytics-service:latest
    networks:
      - budget
    environment:
      POSTGRES_HOST: budget-analytics-pg
      POSTGRES_PORT: 5432
      POSTGRES_DB: budget_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EUREKA_SERVER: eureka:8761
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
      budget_analytics_pg:
        condition: service_healthy
      kafka:
        condition: service_started
  kafka:
    image: apache/kafka-native:latest
    hostname: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:29093,BROKER://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    networks:
      - budget
  budget_data_pg:
    image: postgres
    hostname: budget-data-pg
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: budget_data
    volumes:
      - ./docker_data/budget_data:/var/lib/postgresql
    networks:
      - budget
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  budget_analytics_pg:
    image: postgres
    hostname: budget-analytics-pg
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: budget_analytics
    volumes:
      - ./docker_data/budget_analytics:/var/lib/postgresql
    networks:
      - budget
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  budget_data_migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    command: --url=jdbc:postgresql://budget-data-pg:5432/budget_data --username=postgres --password=qwerty123 --changelog-file=data/db/master.yaml update
    depends_on:
      budget_data_pg:
        condition: service_healthy
    networks:
      - budget
  budget_analytics_migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    command: --url=jdbc:postgresql://budget-analytics-pg:5432/budget_analytics --username=postgres --password=qwerty123 --changelog-file=analytics/db/master.yaml update
    depends_on:
      budget_analytics_pg:
        condition: service_healthy
    networks:
      - budget
networks:
  budget: