spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: data-service-auth-register
              uri: lb://data-service
              predicates:
                - Path=/api/auth/register
              filters:
                - RemoveRequestHeader=Cookie
            - id: data-service-protected
              uri: lb://data-service
              predicates:
                - Path=/api/budget/**,/api/category/**,/api/transaction/**,/api/user/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: analytics-service-protected
              uri: lb://analytics-service
              predicates:
                - Path=/api/analytics/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: ai-agent-protected
              uri: lb://ai-agent
              predicates:
                - Path=/api/ai/**
              filters:
                - RemoveRequestHeader=Cookie
              metadata:
                response-timeout: -1
          globalcors:
           cors-configurations:
               '[/**]':
                   allowedOrigins: "http://localhost:5173"
                   allowedMethods:
                     - GET
                     - POST
                     - PUT
                     - DELETE
                     - OPTIONS
                   allowedHeaders: "*"
                   allowCredentials: true
                   maxAge: 3600

server:
  reactive:
    session:
      timeout: ${SESSION_TIMEOUT:30m}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
